FROM php:8.1-apache

# Aktifkan modul Apache
RUN a2enmod rewrite

# Copy seluruh isi folder ke dalam container
COPY . /var/www/html/

# Set DocumentRoot ke folder public
RUN sed -i 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/000-default.conf

# Set hak akses
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
