# Gunakan base image PHP + Apache
FROM php:8.1-apache

# Salin semua isi ke container
COPY . /var/www/html/

# Aktifkan modul rewrite (opsional untuk .htaccess)
RUN a2enmod rewrite

# Pindahkan folder public sebagai root dokumen
WORKDIR /var/www/html/public

# Buka port 80
EXPOSE 80
